config/routes.rb
Rails.application.routes.draw do

  root 'public#index'
  get 'home', to: 'dashboard#index'
  devise_for :users, controllers: { registrations: "registrations",
                                  omniauth_callbacks: "omniauth_callbacks"}

  resources :friends, only: [:index, :destroy]
  resources :friend_requests, except: [:edit, :show]
  get 'sent_requests', to: 'friend_requests#sent_requests'

  resources :posts do
    collection do
      get 'my_blogs'
    end
    resources :comments, only: [:create, :destroy, :edit, :update, :new, :show]
  end
  post '/rate' => 'rater#create', :as => 'rate'

  resources :comments, only: :create do
    member do
      get :liked_by
    end
    resources :likes, only: [:create, :destroy]
  end

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :relationships,  only: [:create, :destroy]

  resources :subscribes, only: [:create, :destroy] do
    collection do
      get 'unsubscribe'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :children, class_name: "Comment", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent, class_name: "Comment"
  has_many :likes, dependent: :destroy
  has_many :liked_by, through: :likes, source: :user

  validates :content, presence: true, length: { maximum: 10000}
  validates :post_id, presence: true
  validates :user_id, presence: true

  def get_children
    self.children.includes(:likes, :user)
  end

  def self.get_user_likes(comments, user_id)
    current_user_likes = []
    comments.each do |comment|
      like = Like.find_by(:comment_id => comment.id, :user_id => user_id)
      current_user_likes << like
    end
    current_user_likes
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	after_create :send_email_to_subscribers

	ratyrate_rateable "content"
	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :title, presence: true, length: {maximum: 150}
	validates :content, presence: true

	def to_param
    [id, title.parameterize].join("-")
  end

  def get_root_comments
		self.comments.where(parent_id: nil).includes(:user, :children, :likes)
	end

	private

	def send_email_to_subscribers
	  Subscribe.all.each do |subscribe|
	  	SubscribeMailer.delay.send_email(subscribe.email, self)
		end
	end

	def self.search(search)
  	where("title LIKE :search", {search: "%#{search}%"}).order("updated_at DESC")
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :get_post, except: :liked_by
	before_action :check_user, only: [:edit, :update]
	before_action :check_post_user, only: :destroy

	def new
		@comment = Comment.find_by(id: params[:comment_id])
    @left_margin = calculate_left_margin(@comment)
		respond_to do |format|
			format.js
		end
	end

	def create
		@comment = Comment.create(comment_params.merge({post_id: @post.id, user_id: current_user.id}))
    @like = Like.find_by(:comment_id => @comment.id, :user_id => current_user.id)
    @parent_comment = Comment.find_by(id: @comment.parent_id)
    @no_of_children = set_no_of_children(@parent_comment)
    @left_margin = calculate_left_margin(@parent_comment)
		respond_to do |format|
			format.html {redirect_to post_path(@post)}
			format.js
		end
	end

	def destroy
		@comment_ids = [@comment.id]
		if(@comment.children)
			find_all_child_comment(@comment.children)
		end
    @comment.destroy
    if @comment.parent_id
      @no_of_children = Comment.find_by(id: @comment.parent_id).children.length
    end
    respond_to do |format|
    	format.html {redirect_to post_path(@post)}
    	format.js
    end
  end

  def edit
  	respond_to do |format|
  		format.js
  	end
  end

  def update
    @like = Like.find_by(:comment_id => @comment.id, :user_id => current_user.id)
  	@comment.update(comment_params)
  	respond_to do |format|
  		format.js
  	end
  end

  def liked_by
  	@comment = Comment.find_by(id: params[:id])
  	@users = @comment.liked_by.page params[:page]
  	@relationships = User.fetch_user_relationship(@users, current_user)
		@friendships = User.fetch_user_friendship(@users, current_user)
		@friend_requests = User.fetch_user_friend_request(@users, current_user)
  end

  def show
    @comment = @post.comments.find_by(id: params[:id])
    redirect_to post_path(@post) unless @comment
    @comments = @comment.get_children
    @current_user_likes = Comment.get_user_likes(@comments, current_user.id)
    @left_margin = calculate_left_margin(@comment)
    respond_to do |format|
      format.js
    end
  end

	private

		def comment_params
			params.require(:comment).permit(:content, :parent_id, :base_id, :level)
		end

		def get_post
			@post = Post.find_by(id: params[:post_id])
			redirect_to posts_path unless @post
		end

		def check_post_user
			@comment = @post.comments.find_by(id: params[:id])
			redirect_to post_path(@post) unless @comment
			if @post.user != current_user
        check_user
      end
		end

		def check_user
			@comment = @post.comments.find_by(id: params[:id])
			redirect_to post_path(@post) unless @comment
      if @comment.user != current_user
        redirect_to @post, notice: "Cannot access other user comment page"
      end
    end

		def find_all_child_comment comments
			comments.each do |comment|
				@comment_ids.push(comment.id)
				if(comment.children)
					find_all_child_comment(comment.children)
				end
			end
		end

    def calculate_left_margin(comment)
      if comment
        left_margin = 100
        level = comment.level
        while level >= 0
          left_margin *= 0.9
          level = level - 1
        end
        left_margin
      else
        left_margin = 0
      end
    end

    def set_no_of_children(parent_comment)
      no_of_children = 0
      if parent_comment
        no_of_children = parent_comment.children.length
      end
      no_of_children
    end
end

app/views/comments/_comment.html.erb
<div id="full_comment_<%= comment.id %>" class="full-comment">
	<%= render partial: "comments/comment_content", locals: {comment: comment, like: like, post: post} %>
</div>

app/views/comments/_comment_content.html.erb
<div class="comment">
	<div class="image">
		<%= render partial: "shared/user_image", locals: {user: comment.user}%>
	</div>
	<div class="comment-contents">
		<%= link_to comment.user.username, comment.user %> <%= comment.content %>
	</div>
	<div style="clear:both"></div>
</div>

<div class="comment-reply-delete">
	<span id="like_count_<%= comment.id %>">
		<%= render partial: "shared/like_count", locals: {comment: comment} %>
	</span>
	<% if !like  %>
		<span id="like_<%= comment.id %>">
			<%= link_to "Like", comment_likes_path(comment), method: :post, remote: true %>
		</span>
	<% else %>
		<span id="unlike_<%= comment.id %>">
			<%= link_to "Unlike", comment_like_path(comment, like), method: :delete, remote: true %>
		</span>
	<% end %>

	<span>
		<%= link_to "Reply", new_post_comment_path(post, comment_id: comment.id,), remote: true %>
	</span>
	<span class="time-ago">
		<%= " - #{time_ago_in_words(comment.created_at)}" %>
	</span>

	<span class="edit-delete-comment">
		<% if comment.user == current_user %>
			<%= link_to  "<i class=\"glyphicon glyphicon-pencil\"></i>".html_safe,
																edit_post_comment_path(post, comment), remote: true %>
		<% end %>
		<% if comment.user == current_user || @post.user == current_user %>
			<%= link_to "<i class=\"glyphicon glyphicon-trash\"></i>".html_safe, [post, comment],
														method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
		<% end %>
	</span>

	<% if (comment.children.length > 0) %>
		<%= link_to "Replies", post_comment_path(post, comment), remote: true, id: "link_to_replies_#{comment.id}" %>
		<span id="reply_<%= comment.id %>", class="reply"> Replies </span>
		<span id="hide_<%= comment.id %>", class="no-display"> Hide </span>
	<% end %>
</div>

app/views/comments/_comment_form.html.erb
<div class="form-div">
  <div class="image">
    <%= render partial: "shared/user_image", locals: {user: comment.user} %>
  </div>
	<div class="comment-form">
		<%= form_for([post, post.comments.build], remote: true, id: "comment_form_#{comment.id}") do |f| %>
			<%= f.hidden_field :parent_id, :value => comment.id %>
			<%= f.hidden_field :level, :value => comment.level + 1 %>
			<% if !comment.base_id %>
				<%= f.hidden_field :base_id, :value => comment.id %>
			<% else %>
				<%= f.hidden_field :base_id, :value => comment.base_id %>
			<%end%>
			<%= f.text_field :content, placeholder: "Comment", autocomplete: "off", class: 'form-control',
																	id: "comment_content_#{comment.id}" %>
			<%= f.submit "Comment", class:"hide" %>
		<% end %>
	</div>
	<div style="clear:both"></div>
</div>

app/views/comments/_edit_comment_form.html.erb
<div class="image">
	<%= render partial: "shared/user_image", locals: {user: post.user} %>
</div>
<div class="comment-form">
	<%= form_for([post, comment], method: :put,
												remote: true, id: "comment_form_#{comment.id}") do |f| %>
		<%= f.text_field :content, autocomplete: "off", class: 'form-control',
																id: "comment_content_#{comment.id}", value: comment.content %>
		<%= f.submit "Comment", class:"hide" %>
	<% end %>
</div>
<div style="clear:both"></div>

app/views/comments/create.js.erb
<% if @comment.parent_id != nil %>
	$('#comment_content_<%= @parent_comment.id %>').val('');
  $('#display_comment_<%= @parent_comment.id %>').css("margin-left", <%= @left_margin %>);
	$("#display_comment_<%= @parent_comment.id %>").
              append("<%= j render partial: 'comments/comment', locals: {comment: @comment, like: @like, post: @post} %>");
	$("#reply_div_<%= @parent_comment.id %>").html('');
	$('<div id="display_comment_<%= @comment.id %>"></div>').appendTo("#display_comment_<%= @parent_comment.id %>");
	$('<div id="reply_div_<%= @comment.id %>"></div>').appendTo("#display_comment_<%= @parent_comment.id %>");
<% else %>
	$('.comment-content').val('');
	$("#base_comment").append("<%= j render partial: 'comments/comment',
                              locals: {comment: @comment, like: @like, post: @post} %>");
	$('<div id="display_comment_<%= @comment.id %>"></div>').appendTo("#base_comment");
	$('<div id="reply_div_<%= @comment.id %>"></div>').appendTo("#base_comment");
<% end %>

<% if @no_of_children == 1 %>
  $('#full_comment_<%= @parent_comment.id %>').find(".comment-reply-delete").
                        append('<span id="reply_<%= @parent_comment.id %>", class="reply"> Replies </span>');
  $('#full_comment_<%= @parent_comment.id %>').find(".comment-reply-delete").
                        append('<span id="hide_<%= @parent_comment.id %>", class="no-display"> Hide </span>');
  $("#hide_<%= @parent_comment.id %>").show();
<% end %>

app/views/comments/destroy.js.erb
<% @comment_ids.each do |comment_id| %>
	$("#full_comment_<%= comment_id %>").remove();
	$("#reply_div_<%= comment_id %>").remove();
<% end %>

<% if @no_of_children == 0 %>
  $("#full_comment_<%= @comment.parent_id %>").find('#reply_<%= @comment.parent_id %>').remove();
  $("#full_comment_<%= @comment.parent_id %>").find('#hide_<%= @comment.parent_id %>').remove();
<% end %>

app/views/comments/edit.js.erb
$("#full_comment_<%= @comment.id %>").
            html("<%= j render partial: 'edit_comment_form', locals: {post: @post, comment: @comment}%>");

app/views/comments/liked_by.html.erb
<h1 id="header_id"> Liked By </h1>
<%= paginate @users %>
<%= render partial: "shared/users", locals: {users: @users, relationships: @relationships,
	  																			friendships: @friendships, friend_requests: @friend_requests} %>
<%= paginate @users %>

app/views/comments/new.js.erb
$("#reply_div_<%= @comment.id %>").css("margin-left", <%= @left_margin %>);
$("#reply_div_<%= @comment.id %>").
              append("<%= j render partial: 'comments/comment_form', locals: {post: @post, comment: @comment} %>");

app/views/comments/show.js.erb
$('#link_to_replies_<%= @comment.id %>').remove();
$('#display_comment_<%= @comment.id %>').css("margin-left", <%= @left_margin %>);
$('#display_comment_<%= @comment.id %>').html('<%= j render partial: "shared/comment", locals: {comments: @comments,
                                                                post: @post, current_user_likes: @current_user_likes } %>');
$('#hide_<%= @comment.id %>').show();

app/views/comments/update.js.erb
$("#full_comment_<%= @comment.id %>").
              html("<%= j render partial: 'comment_content', locals: {post: @post, comment: @comment, like: @like} %>");