config/routes.rb
Rails.application.routes.draw do

  root 'public#index'
  get 'home', to: 'dashboard#index'
  devise_for :users, controllers: { registrations: "registrations",
                                  omniauth_callbacks: "omniauth_callbacks"}

  resources :friends, only: [:index, :destroy]
  resources :friend_requests, except: [:edit, :show]
  get 'sent_requests', to: 'friend_requests#sent_requests'

  resources :posts do
    collection do
      get 'my_blogs'
    end
    resources :comments, only: [:create, :destroy, :edit, :update, :new, :show]
  end
  post '/rate' => 'rater#create', :as => 'rate'

  resources :comments, only: :create do
    member do
      get :liked_by
    end
    resources :likes, only: [:create, :destroy]
  end

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :relationships,  only: [:create, :destroy]

  resources :subscribes, only: [:create, :destroy] do
    collection do
      get 'unsubscribe'
    end
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
	before_action :get_friend, only: :destroy

  def index
  	@friends = current_user.friends
    @user = User.find_by(id: @friend_request.friend_id)
  end

  def destroy
    redirect_to :back unless @friend
    current_user.remove_friend(@friend)
    respond_to do |format|
      format.html {redirect_to friends_path}
      format.js
    end
  end

  private

  def get_friend
    @friend = current_user.friends.find_by(id: params[:id])
  end
end

app/views/friends/destroy.js.erb
$('#friends_list_count').html("<%= j render partial: 'shared/friends_list_count'%>");
$('#friend_list_<%= @friend.id %>').remove();
$('.notice-msg').html("Successfully removed from your friends list!");
timeOut();

app/views/friends/index.html.erb
<h1 id="header_id">My Friends</h1>

<table class="table table-hover">
  <thead>
  	<th>Friends</th>
  </thead>
	<% @friends.each do |user| %>
		<tr id="friend_list_<%= user.id %>">
			<td colspan="8"> <%= render partial: "shared/user_image", locals: {user: user}%>																													<%= link_to "  #{user.username}", user %></td>
			<td colspan="8">
				<%= link_to "Unfriend", friend_path(user), method: :delete, remote: true %>
			</td>
		</tr>
	<% end %>
</table>