config/routes.rb
Rails.application.routes.draw do

  root 'public#index'
  get 'home', to: 'dashboard#index'
  devise_for :users, controllers: { registrations: "registrations",
                                  omniauth_callbacks: "omniauth_callbacks"}

  resources :friends, only: [:index, :destroy]
  resources :friend_requests, except: [:edit, :show]
  get 'sent_requests', to: 'friend_requests#sent_requests'

  resources :posts do
    collection do
      get 'my_blogs'
    end
    resources :comments, only: [:create, :destroy, :edit, :update, :new, :show]
  end
  post '/rate' => 'rater#create', :as => 'rate'

  resources :comments, only: :create do
    member do
      get :liked_by
    end
    resources :likes, only: [:create, :destroy]
  end

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :relationships,  only: [:create, :destroy]

  resources :subscribes, only: [:create, :destroy] do
    collection do
      get 'unsubscribe'
    end
  end

end

app/views/shared/_add_friend.html.erb
<td id="add_friend_<%= user.id %>">
  <%= link_to "Add Friend", friend_requests_path(friend_id: user.id), method: :post, remote: true %>
</td>

app/views/shared/_cancel_request.html.erb
<td id="cancel_request_<%= user.id %>" >
	Friend Request Sent/<%= link_to "Cancel Request", friend_request_path(user), :method => :delete, remote: true %>
</td>

app/views/shared/_follow.html.erb
<table class="table table-hover">
  <thead>
    <th colspan="10">Username</th>   
  </thead>
  <tbody>
    <% @users.zip(relationships).each do |user, relationship| %>
      <tr>
        <td colspan="8"> <%= render partial: "shared/user_image", locals: {user: user}%>
                                                <%= link_to "  #{user.username}", user %></td>
        <% if user != current_user %>
           <td colspan="8">
            <% if !relationship %>
              <%= render partial: "shared/link_to_follow", locals: {user: user} %>
            <% else %>
              <%= render partial: "shared/link_to_unfollow", locals: {user: user, relationship: relationship} %>
            <% end %> 
          </td>
        <% end %>  
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_friend_request_count.html.erb
<%= link_to "Friend Requests(#{current_user.received_requests.length})", friend_requests_path %> 

app/views/shared/_friends_list_count.html.erb
<%= link_to "My Friends(#{(current_user.friends).length})", friends_path %>

app/views/shared/_like.html.erb
<span id="like_<%= @comment.id %>">
  <%= link_to "Like", comment_likes_path(@comment), method: :post, remote: true %>
</span>

app/views/shared/_like_count.html.erb
<% if (count = comment.likes.length) > 0 %>
	<%= link_to "#{count}", liked_by_comment_path(comment) %>
	<span class="glyphicon glyphicon-thumbs-up"></span>
<% end %>

app/views/shared/_link_to_follow.html.erb
<td colspan="8" id="follow_<%= user.id %>">
	<%= link_to "Follow", relationships_path(followed_id: user.id),  method: :post, remote: true %>
</td>

app/views/shared/_link_to_unfollow.html.erb
<td colspan="8" id="unfollow_<%= user.id %>">
	<%= link_to "Unfollow", relationship_path(relationship), method: :delete, remote: true %>
</td>

app/views/shared/_post.html.erb
<% if current_user %>
	<span>
	  <% if current_user.id == post.user_id %>
	    <%= link_to 'Edit ', edit_post_path(post) %>| 
	    <%= link_to 'delete ', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>-
	  <% end %>
	  <span class="time-ago"><%= time_ago_in_words(post.created_at) %></span>
	</span >
<% end %>

app/views/shared/_post_manipulation.html.erb
<span>
	<% if current_user.id == post.user_id %>
	  <%= link_to "<i class=\"glyphicon glyphicon-pencil\"></i>".html_safe, edit_post_path(post) %> | 
	  <%= link_to "<i class=\"glyphicon glyphicon-trash\"></i>".html_safe, post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
	<span class="time-ago"> <%= time_ago_in_words(post.created_at) %> ago</span>
</span >

app/views/shared/_unlike.html.erb
<span id="unlike_<%= @comment.id %>">
	<%= link_to "Unlike", comment_like_path(@comment, @like), method: :delete, remote: true %>
</span>

app/views/shared/_user_image.html.erb
<% if user.image.present? %>
  <%= image_tag user.image.thumb.url, class: "missing-image" %>
<% else %>
  <img src="<%= asset_path( 'blank-person.png' ) %>" class="missing-image"/>
<% end %>

app/views/shared/_user_relationship.html.erb
<% if friendship %>
  <td colspan="8"> Friends</td>
<% elsif friend_request[:received_request] %>
  <td colspan="8"> Respond to Request </td> 
<% elsif !friend_request[:sent_request] %>
  <%= render partial: "shared/add_friend", locals: {user: user} %>
<% else %>
  <%= render partial: "shared/cancel_request", locals: {user: user} %>
<% end %>
<% if !relationship %>
  <%= render partial: "shared/link_to_follow", locals: {user: user} %>
<% else %>
  <%= render partial: "shared/link_to_unfollow", locals: {user: user, relationship: relationship} %>
<% end %> 