config/routes.rb
Rails.application.routes.draw do

  root 'public#index'
  get 'home', to: 'dashboard#index'
  devise_for :users, controllers: { registrations: "registrations",
                                  omniauth_callbacks: "omniauth_callbacks"}

  resources :friends, only: [:index, :destroy]
  resources :friend_requests, except: [:edit, :show]
  get 'sent_requests', to: 'friend_requests#sent_requests'

  resources :posts do
    collection do
      get 'my_blogs'
    end
    resources :comments, only: [:create, :destroy, :edit, :update, :new, :show]
  end
  post '/rate' => 'rater#create', :as => 'rate'

  resources :comments, only: :create do
    member do
      get :liked_by
    end
    resources :likes, only: [:create, :destroy]
  end

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :relationships,  only: [:create, :destroy]

  resources :subscribes, only: [:create, :destroy] do
    collection do
      get 'unsubscribe'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	after_create :send_email_to_subscribers

	ratyrate_rateable "content"
	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :title, presence: true, length: {maximum: 150}
	validates :content, presence: true

	def to_param
    [id, title.parameterize].join("-")
  end

  def get_root_comments
		self.comments.where(parent_id: nil).includes(:user, :children, :likes)
	end

	private

	def send_email_to_subscribers
	  Subscribe.all.each do |subscribe|
	  	SubscribeMailer.delay.send_email(subscribe.email, self)
		end
	end

	def self.search(search)
  	where("title LIKE :search", {search: "%#{search}%"}).order("updated_at DESC")
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_authenticated_user?, only: [:edit, :update, :destroy]

  def index
    if params[:search]
      @posts = Post.search(params[:search]).page params[:page]
    else
      @posts = Post.order("updated_at DESC").page params[:page]
    end
  end

  def show
    @following_count = @post.user.following.count
    @followers_count = @post.user.followers.count
    @post_user = @post.user.name
    @comments = @post.get_root_comments
    @current_user_likes = Comment.get_user_likes(@comments, current_user.id)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  def my_blogs
    if params[:search]
      @posts = current_user.posts.search(params[:search]).page params[:page]
    else
      @posts = current_user.posts.order("updated_at DESC").page params[:page]
    end
  end

  private
    def get_post
      @post = Post.find_by(id: params[:id])
      unless @post
        redirect_to posts_path, notice: 'The post you are looking for does not exist'
      end
    end

    def check_authenticated_user?
      if @post.user != current_user
        redirect_to posts_path, notice: "Cannot access other user post page"
      end
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/views/posts/_form.html.erb
<%= tinymce %>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", id: "title" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class: "tinymce" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div id="posts" >
  <% if !@posts.present? %>
    <p><b>There are no posts with name like: <%= params[:search] %>.</b></p>
  <% else %>  
    <%= paginate @posts %>
      <table class="table table-hover">
        <tbody>
          <% @posts.each do |post| %>
            <div class="post">
              <div class="post-title-wrap"> <%= link_to post.title, post %> </div>
              <div class="show-less-content">
                <div id="post_content">
                  <%= post.content.html_safe %>
                </div>
              </div>
              <%= render partial: "shared/post_manipulation", locals: {post: post} %>
            </div>   
            <br><br>
          <% end %>
        </tbody>
      </table>
    <%= paginate @posts %>
  <% end %>  
</div>

app/views/posts/edit.html.erb
<h1 id="header_id">Editing Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="header_id">Listing Posts</h1>
<%= render 'layouts/subscribe' %>

<%= form_tag(posts_path, :method => "get", id: "search_post") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search posts", autocomplete: "off", value: nil %>
  <%= button_tag "", type: 'submit', class: "button-search glyphicon glyphicon-search" %>
<% end %>
<br>
<br>
<%= render "posts" %>

app/views/posts/my_blogs.html.erb
<h1 id="header_id">My Posts</h1>
<%= render 'layouts/subscribe' %>

<%= form_tag(my_blogs_posts_path, :method => "get", id: "search_post") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search posts", autocomplete: "off", value: nil %>
  <%= button_tag "", type: 'submit', class: "button-search glyphicon glyphicon-search" %>
<% end %>
<br>
<br>
<%= render "posts" %>

app/views/posts/new.html.erb
<h1 id="header_id">New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'layouts/subscribe' %>

<div id="post_title">
  <u><%= @post.title %></u>
</div>
<div id="post_content">
  <%= @post.content.html_safe %>
</div>

<%= render partial: "shared/post_manipulation", locals: {post: @post} %>

<div>
  <% if @post.user_id != current_user.id %>
    <span> --posted by: <%= link_to @post_user, user_path(@post.user_id) %> </strong>
          <%= link_to " #{@followers_count} followers", followers_user_path(@post.user_id) %>
          <%= link_to " #{@following_count} following", following_user_path(@post.user_id) %>
    </span>
  <% end %>
</div>

<%= rating_for @post, 'content', disable_after_rate: false, enable_half: true %>

<% if @comments.any? %>
  <h3>Comments:</h3>
  <%= render partial: "shared/comment", locals: {comments: @comments, post: @post,
                                                current_user_likes: @current_user_likes } %>
<% end %>

<div id="base_comment"></div>

<h4><strong>Add a comment:</strong></h4>

<div >
  <div class="image">
    <%= render partial: "shared/user_image", locals: {user: current_user} %>
  </div>
  <div class="comment-form">
    <%= form_for([@post, @post.comments.build], remote: true, class: "comment-form") do |f| %>
      <%= f.text_field :content, placeholder: "Comment", autocomplete: "off", class: 'form-control
                                                                                  comment-content' %>
      <%= f.submit "Comment", class:"hide" %>
    <% end %>
  </div>
  <div style="clear:both"></div>
</div>